name: Build Test and Publish Nightly Packages

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: ["nightly-build"]
  push:
    branches:
      - nightly

jobs:



  build-macos:
    runs-on: macos-latest

    strategy:
      max-parallel: 4
      matrix:
        target: [
          macos-x86_64,
        ]
        include:
          - target: macos-x86_64
            platform: macos
            platform_version: x86_64

    steps:
    - uses: actions/checkout@v1
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb/edgedb-pkg

    - name: Build (${{ matrix.target }})
      env:
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        SRC_REF: "nightly"
      run: |
        edgedb-pkg/integration/macos/build.sh

    - name: Test (${{ matrix.target }})
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
      run: |
        edgedb-pkg/integration/macos/test.sh

    - uses: actions/upload-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}





  publish-macos:
    needs: [build-macos]
    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        target: [
          macos-x86_64,
        ]
        include:
          - target: macos-x86_64
            platform: macos
            platform_version: x86_64

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

    - uses: actions/checkout@v1
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb/edgedb-pkg

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: "${{ matrix.target }}"

    - name: Publish (${{ matrix.target }})
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"
      run: |
        edgedb-pkg/integration/macos/publish.sh



